export const FALLBACK = [
  {
    id: 1,
    tmdb_id: 27205,
    title: "Inception",
    year: 2010,
    director: "Christopher Nolan",
    runtime: 148,
    rating: 8.8,
    genres: ["Sci-Fi", "Thriller"],
    blurb: "A thief who steals secrets through dream infiltration takes on one final impossible job: planting an idea.",
    poster_path: "/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
    backdrop_path: "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg"
  },
  {
    id: 2,
    tmdb_id: 496243,
    title: "Parasite",
    year: 2019,
    director: "Bong Joon-ho",
    runtime: 132,
    rating: 8.6,
    genres: ["Drama", "Thriller"],
    blurb: "Two families on opposite ends of Seoul's class divide collide, with consequences neither could have foreseen.",
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg"
  },
  {
    id: 3,
    tmdb_id: 120467,
    title: "The Grand Budapest Hotel",
    year: 2014,
    director: "Wes Anderson",
    runtime: 99,
    rating: 8.1,
    genres: ["Comedy", "Drama"],
    blurb: "A legendary concierge and his protege become entangled in a theft, a will, and the fall of a fictional empire.",
    poster_path: "/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    backdrop_path: "/jK65srQczOKTpW62wPxwwKztGgE.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/jK65srQczOKTpW62wPxwwKztGgE.jpg"
  },
  {
    id: 4,
    tmdb_id: 76341,
    title: "Mad Max: Fury Road",
    year: 2015,
    director: "George Miller",
    runtime: 120,
    rating: 8.1,
    genres: ["Action", "Adventure"],
    blurb: "A hardened drifter and a rebellious commander lead a convoy across a scorched wasteland.",
    poster_path: "/ulcAi4dKpAjHwYGS08vNyx9H6I9.jpg",
    backdrop_path: "/uT895WNwm0aIJRtGizcQhrejWUo.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/ulcAi4dKpAjHwYGS08vNyx9H6I9.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/uT895WNwm0aIJRtGizcQhrejWUo.jpg"
  },
  {
    id: 5,
    tmdb_id: 129,
    title: "Spirited Away",
    year: 2001,
    director: "Hayao Miyazaki",
    runtime: 125,
    rating: 8.6,
    genres: ["Animation", "Fantasy"],
    blurb: "A young girl trapped in a spirit world must work in a bathhouse to save her parents and find her way home.",
    poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backdrop_path: "/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg"
  },
  {
    id: 6,
    tmdb_id: 155,
    title: "The Dark Knight",
    year: 2008,
    director: "Christopher Nolan",
    runtime: 152,
    rating: 9.0,
    genres: ["Action", "Crime", "Drama"],
    blurb: "Gotham's fragile order collapses as a masked vigilante faces an agent of pure chaos.",
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop_path: "/9FE5eD92WfVCiivM9Pq9GVSrlWk.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/9FE5eD92WfVCiivM9Pq9GVSrlWk.jpg"
  },
  {
    id: 7,
    tmdb_id: 194,
    title: "Amélie",
    year: 2001,
    director: "Jean-Pierre Jeunet",
    runtime: 122,
    rating: 8.3,
    genres: ["Comedy", "Romance"],
    blurb: "A shy Parisian waitress decides to secretly orchestrate happiness for the people around her.",
    poster_path: "/nSxDa3M9aMvGVLoItzWTepQ5h5d.jpg",
    backdrop_path: "/6n53UI4mX9QMfe2S0Pgt8mGebY1.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/nSxDa3M9aMvGVLoItzWTepQ5h5d.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/6n53UI4mX9QMfe2S0Pgt8mGebY1.jpg"
  },
  {
    id: 8,
    tmdb_id: 419430,
    title: "Get Out",
    year: 2017,
    director: "Jordan Peele",
    runtime: 104,
    rating: 7.7,
    genres: ["Horror", "Mystery"],
    blurb: "A weekend visit to his girlfriend's family estate reveals something far more sinister beneath its hospitality.",
    poster_path: "/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    backdrop_path: "/bBQHALHRAaaORlPNXv7fNcRXYdx.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/bBQHALHRAaaORlPNXv7fNcRXYdx.jpg"
  },
  {
    id: 9,
    tmdb_id: 244786,
    title: "Whiplash",
    year: 2014,
    director: "Damien Chazelle",
    runtime: 106,
    rating: 8.5,
    genres: ["Drama", "Music"],
    blurb: "A young drummer's pursuit of greatness collides with the brutal methods of a relentless instructor.",
    poster_path: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdrop_path: "/fRGxZuo7jJUWQsVg9PREb98Aclp.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/fRGxZuo7jJUWQsVg9PREb98Aclp.jpg"
  },
  {
    id: 10,
    tmdb_id: 329865,
    title: "Arrival",
    year: 2016,
    director: "Denis Villeneuve",
    runtime: 116,
    rating: 7.9,
    genres: ["Sci-Fi", "Drama"],
    blurb: "A linguist is recruited to decode an alien language before rising global panic turns to war.",
    poster_path: "/pEzNVQfdzYDzVK0XqxERIw2x2se.jpg",
    backdrop_path: "/8MUZz7oPXQftFTslZpRP3CVMOoq.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/pEzNVQfdzYDzVK0XqxERIw2x2se.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/8MUZz7oPXQftFTslZpRP3CVMOoq.jpg"
  },
  {
    id: 11,
    tmdb_id: 546554,
    title: "Knives Out",
    year: 2019,
    director: "Rian Johnson",
    runtime: 130,
    rating: 7.9,
    genres: ["Mystery", "Comedy"],
    blurb: "A family patriarch's sudden death draws a detective into a web of motive, money, and misdirection.",
    poster_path: "/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
    backdrop_path: "/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg"
  },
  {
    id: 12,
    tmdb_id: 278,
    title: "The Shawshank Redemption",
    year: 1994,
    director: "Frank Darabont",
    runtime: 142,
    rating: 9.3,
    genres: ["Drama"],
    blurb: "A wrongly convicted banker forms an unlikely friendship that carries him through two decades behind bars.",
    poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    backdrop_path: "/pNjh59JSxChQktamG3LMp9ZoQzp.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/pNjh59JSxChQktamG3LMp9ZoQzp.jpg"
  },
  {
    id: 13,
    tmdb_id: 1417,
    title: "Pan's Labyrinth",
    year: 2006,
    director: "Guillermo del Toro",
    runtime: 118,
    rating: 8.2,
    genres: ["Fantasy", "Drama"],
    blurb: "A girl escapes the horrors of postwar Spain into a mythic underworld with its own brutal rules.",
    poster_path: "/z7xXihu5wHuSMWymq5VAulPVuvg.jpg",
    backdrop_path: "/6G6nqSW9S7EHA9HrYl0Z8uo2H7f.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/z7xXihu5wHuSMWymq5VAulPVuvg.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/6G6nqSW9S7EHA9HrYl0Z8uo2H7f.jpg"
  },
  {
    id: 14,
    tmdb_id: 313369,
    title: "La La Land",
    year: 2016,
    director: "Damien Chazelle",
    runtime: 128,
    rating: 8.0,
    genres: ["Romance", "Music"],
    blurb: "An aspiring actress and a jazz pianist chase their dreams in a city built on reinvention.",
    poster_path: "/uDO8zWDhfWwoFdKS4fzkVJt0Rf0.jpg",
    backdrop_path: "/nlPCdZlHtRNcF6C9hzUH4ebmV1w.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/uDO8zWDhfWwoFdKS4fzkVJt0Rf0.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/nlPCdZlHtRNcF6C9hzUH4ebmV1w.jpg"
  },
  {
    id: 15,
    tmdb_id: 6977,
    title: "No Country for Old Men",
    year: 2007,
    director: "Coen Brothers",
    runtime: 122,
    rating: 8.1,
    genres: ["Crime", "Thriller"],
    blurb: "A hunter stumbles onto blood money in the desert and into the path of an unstoppable killer.",
    poster_path: "/6d5XOczc226jECq0LIX0siKtgHR.jpg",
    backdrop_path: "/gddUsvfyySrM5k8B8wwJy2VRlBx.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/6d5XOczc226jECq0LIX0siKtgHR.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/gddUsvfyySrM5k8B8wwJy2VRlBx.jpg"
  },
  {
    id: 16,
    tmdb_id: 157336,
    title: "Interstellar",
    year: 2014,
    director: "Christopher Nolan",
    runtime: 169,
    rating: 8.7,
    genres: ["Sci-Fi", "Adventure"],
    blurb: "A former pilot leads a mission through a wormhole to find humanity a new home before Earth runs out of time.",
    poster_path: "/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",
    backdrop_path: "/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg"
  },
  {
    id: 17,
    tmdb_id: 545611,
    title: "Everything Everywhere All at Once",
    year: 2022,
    director: "Daniels",
    runtime: 140,
    rating: 7.8,
    genres: ["Sci-Fi", "Comedy"],
    blurb: "An overwhelmed laundromat owner must jump across parallel universes to save all of existence.",
    poster_path: "/u68AjlvlutfEIcpmbYpKcdi09ut.jpg",
    backdrop_path: "/ss0Os3uWJfQAENILHZUdX8Tt1OC.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/u68AjlvlutfEIcpmbYpKcdi09ut.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/ss0Os3uWJfQAENILHZUdX8Tt1OC.jpg"
  },
  {
    id: 18,
    tmdb_id: 37799,
    title: "The Social Network",
    year: 2010,
    director: "David Fincher",
    runtime: 120,
    rating: 7.8,
    genres: ["Drama", "Biography"],
    blurb: "A Harvard dorm-room idea splinters friendships on its way to becoming a global empire.",
    poster_path: "/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
    backdrop_path: "/1PXwh3nJzgRkkYnqfWInJNypeL4.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/1PXwh3nJzgRkkYnqfWInJNypeL4.jpg"
  },
  {
    id: 19,
    tmdb_id: 354912,
    title: "Coco",
    year: 2017,
    director: "Lee Unkrich",
    runtime: 105,
    rating: 8.4,
    genres: ["Animation", "Family"],
    blurb: "A boy chasing a dream of music crosses into the Land of the Dead to uncover his family's hidden past.",
    poster_path: "/6Ryitt95xrO8KXuqRGm1fUuNwqF.jpg",
    backdrop_path: "/g7CHF8gTLGooTbP4GznIGwaqAGL.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/6Ryitt95xrO8KXuqRGm1fUuNwqF.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/g7CHF8gTLGooTbP4GznIGwaqAGL.jpg"
  },
  {
    id: 20,
    tmdb_id: 335984,
    title: "Blade Runner 2049",
    year: 2017,
    director: "Denis Villeneuve",
    runtime: 164,
    rating: 8.0,
    genres: ["Sci-Fi", "Mystery"],
    blurb: "A new blade runner unearths a buried secret that could unravel what's left of society's fragile order.",
    poster_path: "/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdrop_path: "/gNdLJU9TxrpGx4dkZidjys3fyy0.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/gNdLJU9TxrpGx4dkZidjys3fyy0.jpg"
  },
  {
    id: 21,
    tmdb_id: 376867,
    title: "Moonlight",
    year: 2016,
    director: "Barry Jenkins",
    runtime: 111,
    rating: 7.4,
    genres: ["Drama"],
    blurb: "Three chapters trace a boy's quiet, searching path toward understanding who he is.",
    poster_path: "/qLnfEmPrDjJfPyyddLJPkXmshkp.jpg",
    backdrop_path: "/jm1oD3eB08LImSwL1LrzF9AJQ5b.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/qLnfEmPrDjJfPyyddLJPkXmshkp.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/jm1oD3eB08LImSwL1LrzF9AJQ5b.jpg"
  },
  {
    id: 22,
    tmdb_id: 245891,
    title: "John Wick",
    year: 2014,
    director: "Chad Stahelski",
    runtime: 101,
    rating: 7.4,
    genres: ["Action", "Crime"],
    blurb: "A retired hitman is pulled back into the underworld by a single, unforgivable act.",
    poster_path: "/wXqWR7dHncNRbxoEGybEy7QTe9h.jpg",
    backdrop_path: "/ff2ti5DkA9UYLzyqhQfI2kZqEuh.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/wXqWR7dHncNRbxoEGybEy7QTe9h.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/ff2ti5DkA9UYLzyqhQfI2kZqEuh.jpg"
  },
  {
    id: 23,
    tmdb_id: 416477,
    title: "The Big Sick",
    year: 2017,
    director: "Michael Showalter",
    runtime: 120,
    rating: 7.5,
    genres: ["Comedy", "Romance"],
    blurb: "A cross-cultural romance is tested when an illness forces two families to confront each other.",
    poster_path: "/9fJTT8pBxxQsFILJHTtHhdYFr77.jpg",
    backdrop_path: "/fYI8WX2DquAHMqwh5mOMxc6RU5j.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/9fJTT8pBxxQsFILJHTtHhdYFr77.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/fYI8WX2DquAHMqwh5mOMxc6RU5j.jpg"
  },
  {
    id: 24,
    tmdb_id: 493922,
    title: "Hereditary",
    year: 2018,
    director: "Ari Aster",
    runtime: 127,
    rating: 7.3,
    genres: ["Horror", "Drama"],
    blurb: "A family's grief unearths a legacy far darker than anyone imagined.",
    poster_path: "/4GFPuL14eXi66V96xBWY73Y9PfR.jpg",
    backdrop_path: "/gJbTXKNTL6O7r7PzF6ZRkJGBlPp.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/4GFPuL14eXi66V96xBWY73Y9PfR.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/gJbTXKNTL6O7r7PzF6ZRkJGBlPp.jpg"
  },
  {
    id: 25,
    tmdb_id: 1124,
    title: "The Prestige",
    year: 2006,
    director: "Christopher Nolan",
    runtime: 130,
    rating: 8.5,
    genres: ["Drama", "Mystery"],
    blurb: "Two rival magicians escalate their feud until the trick becomes indistinguishable from the sacrifice behind it.",
    poster_path: "/Ag2B2KHKQPukjH7WutmgnnSNurZ.jpg",
    backdrop_path: "/z3br1ub7spqGMkxgjgJSdM4DC21.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/Ag2B2KHKQPukjH7WutmgnnSNurZ.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/z3br1ub7spqGMkxgjgJSdM4DC21.jpg"
  },
  {
    id: 26,
    tmdb_id: 773,
    title: "Little Miss Sunshine",
    year: 2006,
    director: "Dayton & Faris",
    runtime: 101,
    rating: 7.8,
    genres: ["Comedy", "Drama"],
    blurb: "A dysfunctional family's road trip to a beauty pageant becomes a crash course in showing up for each other.",
    poster_path: "/niNdhTpPHSgw22tK0PLjQMV640v.jpg",
    backdrop_path: "/twdtjJm31AExNx73DXaD4KRNU9c.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/niNdhTpPHSgw22tK0PLjQMV640v.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/twdtjJm31AExNx73DXaD4KRNU9c.jpg"
  },
  {
    id: 27,
    tmdb_id: 438631,
    title: "Dune",
    year: 2021,
    director: "Denis Villeneuve",
    runtime: 155,
    rating: 8.0,
    genres: ["Sci-Fi", "Adventure"],
    blurb: "A young heir is thrust into a battle for a desert planet that holds the galaxy's most valuable resource.",
    poster_path: "/v1tRXZ4JtD2Iv6fjkPvT4GiwslV.jpg",
    backdrop_path: "/zRKQW58MBEY078AxkHxEJzUskCl.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/v1tRXZ4JtD2Iv6fjkPvT4GiwslV.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/zRKQW58MBEY078AxkHxEJzUskCl.jpg"
  },
  {
    id: 28,
    tmdb_id: 37165,
    title: "The Truman Show",
    year: 1998,
    director: "Peter Weir",
    runtime: 103,
    rating: 8.2,
    genres: ["Drama", "Comedy"],
    blurb: "A man slowly realizes his entire life has been staged as the world's longest-running television show.",
    poster_path: "/vuza0WqY239yBXOadKlGwJsZJFE.jpg",
    backdrop_path: "/rmiG2uwcNoGFmBKMoa1pIcf514L.jpg",
    poster_url: "https://image.tmdb.org/t/p/w342/vuza0WqY239yBXOadKlGwJsZJFE.jpg",
    backdrop_url: "https://image.tmdb.org/t/p/w1280/rmiG2uwcNoGFmBKMoa1pIcf514L.jpg"
  }
];
